Spring data
ole279889/postservice pull request #13
Opened 2020-10-20 10:11 UTC by ole279889

2020-10-21 09:17 UTC, PavelAndryushenko requested changes
Проделана хорошая работа по изучению JPA, очевиден хороший прогресс. Необходимо выполнить доработки по замечаниям, после чего, запрос можно будет смерджить.

2020-10-21 09:17 UTC, PavelAndryushenko commented on src/main/java/team/mediasoft/study/java/ee/postservice/repository/data_jpa/PostalOperationJPARepository.java
> +    List<PostalOperation> findByPostalItemId(long id);
Вообще, кстати, нужно проработать этот момент - понять, какая практика лучше - объявлять параметры примитивами или обертками?

2020-10-21 09:17 UTC, PavelAndryushenko commented on src/main/java/team/mediasoft/study/java/ee/postservice/service/PostalServiceImpl.java
> +    private PostalOperationJPARepository postalOperationRepository;
Не очень хорошо, что поменялись репозитории - лучше было бы отрефакторить существующие репозитоии. В нашем небольшом приложении это не должно быть проблемой, а вот в большом коммерческом - точно может стать проблемой.

2020-10-21 09:17 UTC, PavelAndryushenko commented on src/main/java/team/mediasoft/study/java/ee/postservice/service/PostalServiceImpl.java
> +        long newItemID = this.postalItemsRepository.save(item).getId();
Если у нас ID генерируется в БД, то далеко не факт, что после вызова save он сгенерируется и вернется - ведь генерация, по идее, произойдет только после flush.
Очень подробно данный механизм описан в этой статье - https://habr.com/ru/post/441386/

2020-10-21 09:17 UTC, PavelAndryushenko commented on src/main/java/team/mediasoft/study/java/ee/postservice/service/PostalServiceImpl.java
> +    private PostalOperationJPARepository postalOperationRepository;
Внедряемые через конструктор зависимости лучше делать финальными.

2020-10-23 10:28 UTC, ole279889 commented on src/main/java/team/mediasoft/study/java/ee/postservice/entity/PostalItem.java
> +                @NamedAttributeNode("type"),
Перенес в static final атрибуты.

2020-10-23 10:28 UTC, ole279889 commented on src/main/java/team/mediasoft/study/java/ee/postservice/repository/data_jpa/PostalItemJPARepository.java
> +package team.mediasoft.study.java.ee.postservice.repository.data_jpa;
Исправлено.

2020-10-23 10:29 UTC, ole279889 commented on src/main/java/team/mediasoft/study/java/ee/postservice/repository/data_jpa/PostalItemJPARepository.java
> +    List<PostalItem> findByRecipientIndex(String s);
Ок

2020-10-23 10:44 UTC, ole279889 commented on src/main/java/team/mediasoft/study/java/ee/postservice/repository/data_jpa/PostalItemJPARepository.java
> +    PostalItem findById(long id);
Добавил возврат Optional с последующей проверкой на isEmpty для методов, кот. могут вернуть null.

2020-10-23 10:46 UTC, ole279889 commented on src/main/java/team/mediasoft/study/java/ee/postservice/repository/data_jpa/PostalOfficesJPARepository.java
> +    List<PostalOffice> findAll();
Перешел на JpaRepository, там findAll возвращает список и findAll() теперь точно не нужен, убрал.

2020-10-23 10:54 UTC, ole279889 commented on src/main/java/team/mediasoft/study/java/ee/postservice/repository/data_jpa/PostalOperationJPARepository.java
> +    List<PostalOperation> findByPostalItemId(long id);
Здесь, думаю, правильнее будет использовать обертки, учитывая, что тип ID в репозиториях передается таким образом: CrudRepository<PostalOperation, Long>, подразумевается, что тип ID будет Long и зря я тут использовал примитив.

2020-10-23 10:55 UTC, ole279889 commented on src/main/java/team/mediasoft/study/java/ee/postservice/service/PostalServiceImpl.java
> +    private PostalOperationJPARepository postalOperationRepository;
Исправлено.

2020-10-23 10:57 UTC, ole279889 commented on src/main/java/team/mediasoft/study/java/ee/postservice/service/PostalServiceImpl.java
> +        long newItemID = this.postalItemsRepository.save(item).getId();
Поменял на saveAndFlush().

2020-11-18 08:29 UTC, merged