Использование Comparator в фильтрации и сортировке
ole279889/postservice pull request #2
Opened 2020-08-26 11:11 UTC by ole279889

2020-09-03 11:28 UTC, PavelAndryushenko requested changes
Код стал ощутимо лучше, это уже очень хорошо, виден хороший прогресс. Оставил замечания, на которые необходимо обратить внимание, чтобы привести код в полный порядок.

2020-09-03 11:28 UTC, PavelAndryushenko commented on src/team/mediasoft/study/java/ee/postservice/service/filtersorting/ComparatorByFieldValue.java
> +    int compare(T objectToCompare, Object fieldValue);
По идее, сравниваться должны объекты одного типа, поэтому, fieldValue, наверное, тоже должен быть T

2020-09-03 11:28 UTC, PavelAndryushenko commented on src/team/mediasoft/study/java/ee/postservice/service/filtersorting/PostalItemFilterSortService.java
> +                            matches = false;
В этом месте matches и так будет false, не нужно его еще раз инициализировать.

2020-09-03 11:28 UTC, PavelAndryushenko commented on src/team/mediasoft/study/java/ee/postservice/service/filtersorting/PostalItemFilterSortService.java
> +                    if (!(comparator.compare(first, second) == 0)) {//Если такая сортировка есть, элементы можно сортировать только в пределах группы
Кажется, что слишком большая когнитивная сложность у этого метода, его желательно разбить

2020-09-03 11:28 UTC, PavelAndryushenko commented on src/team/mediasoft/study/java/ee/postservice/service/filtersorting/PostalItemFilterSortService.java
> +    private Comparator<PostalItem> getComparatorByField(PostalItemFields fieldName) {
Не получается ли так, что мы можем отказаться от ComparatorByFieldValue в пользу обычного компаратора? Есть ли какие-то веские причины иметь этот класс в проекте?

2020-09-03 11:28 UTC, PavelAndryushenko commented on src/team/mediasoft/study/java/ee/postservice/service/filtersorting/PostalItemPrioritySortingParams.java
> +        this.priority = Math.abs(priority);
Тут лучше кидать исключение в том случае, когда будет передано некорректное значение.

2020-09-07 12:38 UTC, ole279889 commented on src/team/mediasoft/study/java/ee/postservice/repository/PostalItemsRepositoryJSON.java
> +        arr.forEach((jsonObject) -> {
Тут все непросто, т.к. JSONArray, который приходится использовать - это некая структура на основе ArrayList, у которой нет метода stream(), т.е., для использования streamApi ее еще нужно преобразовывать, в то же время, JSONArray реализует Iterable и можно без проблем использовать forEach из Iterable..

2020-09-09 13:23 UTC, ole279889 commented on src/team/mediasoft/study/java/ee/postservice/repository/PostalItemsRepositoryJSON.java
> +            throw new RuntimeException("File ITEMS.json not found");
Добавил проверяемое исключение.

2020-09-09 13:24 UTC, ole279889 commented on src/team/mediasoft/study/java/ee/postservice/service/filtersorting/PostalItemFilterSortService.java
> +                    if (!(comparator.compare(first, second) == 0)) {//Если такая сортировка есть, элементы можно сортировать только в пределах группы
Разбито, проверка возможности сортировки вынесена в отдельный метод.

2020-09-09 13:25 UTC, ole279889 commented on src/team/mediasoft/study/java/ee/postservice/service/filtersorting/PostalItemPrioritySortingParams.java
> +        this.priority = Math.abs(priority);
Добавил исключение.

2020-09-09 13:25 UTC, ole279889 commented on src/team/mediasoft/study/java/ee/postservice/service/filtersorting/PostalItemPrioritySortingParams.java
> +        return Integer.compare(priority, params.priority);
Ок

2020-09-09 13:26 UTC, ole279889 commented on src/team/mediasoft/study/java/ee/postservice/service/filtersorting/PostalItemFilterSortService.java
> +                            matches = false;
Да, точно.

2020-09-09 13:27 UTC, ole279889 commented on src/team/mediasoft/study/java/ee/postservice/service/filtersorting/ComparatorByFieldValue.java
> +    int compare(T objectToCompare, Object fieldValue);
Интерфейс переделан, теперь это не Comparator

2020-09-09 13:27 UTC, ole279889 commented on src/team/mediasoft/study/java/ee/postservice/service/filtersorting/ComparatorByFieldValue.java
> +@FunctionalInterface
Ок

2020-09-09 13:27 UTC, ole279889 commented on src/team/mediasoft/study/java/ee/postservice/repository/PostalItemsRepositoryJSON.java
> +            throw new RuntimeException("File ITEMS.json not found");
Добавил проверяемое исключение.

2020-09-10 10:41 UTC, merged