Spring
ole279889/postservice pull request #6
Opened 2020-09-28 12:47 UTC by ole279889

2020-09-29 14:19 UTC, PavelAndryushenko requested changes
Внедрение Спринга прошло вполне успешно, получился хороший код, особенно для первого раза, предлагаю поработать над комментариями, а после - смерджить в мастер.

2020-09-29 14:19 UTC, PavelAndryushenko commented on src/main/java/team/mediasoft/study/java/ee/postservice/entity/dto/ErrorResponseBody.java
> +@JsonClassDescription
Эта аннотация нужна, чтобы добавлять описания полей в генерируемый json - по факту, нам это не нужно, и ее можно убрать

2020-09-29 14:19 UTC, PavelAndryushenko commented on src/main/java/team/mediasoft/study/java/ee/postservice/entity/dto/ItemContainerDTO.java
> +    @JsonGetter("item")
По идее, можно не писать эту аннотацию, если у нас название атрибута класса совпадает с названием атрибута в json

2020-09-29 14:19 UTC, PavelAndryushenko commented on src/main/java/team/mediasoft/study/java/ee/postservice/entity/dto/PostalItemDTO.java
> +    @NotEmpty
Я бы еще добавил какие-то сообщения, которые можно будет отобразить в случае ошибки валидации, чтобы было понятно, какое именно поле не было провалидировано

2020-09-29 14:19 UTC, PavelAndryushenko commented on src/main/java/team/mediasoft/study/java/ee/postservice/exception/handler/GlobalExceptionHandler.java
> +            if (ex instanceof NoItemsFoundException) {
Нет, нужно сделать отдельные методы для каждого типа исключения, так общепринято

2020-09-29 14:19 UTC, PavelAndryushenko commented on src/main/java/team/mediasoft/study/java/ee/postservice/controller/PostalItemsController.java
> +        } catch (NonExistingItemException e) {
Пока не вижу смысла подменять одно исключение другим - можно просто в ControllerAdvice сразу обрабатывать NonExistingItemException

2020-09-29 14:19 UTC, PavelAndryushenko commented on src/main/java/team/mediasoft/study/java/ee/postservice/service/PostalService.java
> +    void officeArrival(PostalItem item, PostalOffice office) throws DataSourceException, DataMistmatchException, NoItemsFoundException, NonExistingItemException;
Тут, кажется, что слишком много проверяемых исключений - не вполне нормальная ситуация, когда их более 1-2-х для такого относительно не сложного бизнес-метода

2020-09-29 14:19 UTC, PavelAndryushenko commented on src/main/java/team/mediasoft/study/java/ee/postservice/repository/dbrepository/DBRepository.java
> +    private static String password;
Эти атрибуты инициализируются в application-context, поэтому, я не уверен, что их теперь нужно оставлять статическими - скорее всего, их лучше сделать не статическими

2020-09-30 12:24 UTC, ole279889 commented on build.gradle
> +    implementation 'org.springframework:spring-core:4.1.1.RELEASE'
Ok

2020-09-30 12:25 UTC, ole279889 commented on build.gradle
> +version null //'1.0.0-SNAPSHOT'
Ok

2020-09-30 12:25 UTC, ole279889 commented on src/main/java/team/mediasoft/study/java/ee/postservice/controller/PostalItemsController.java
> +    @RequestMapping(value = "{id}/status", method = RequestMethod.GET, produces = {MediaType.APPLICATION_JSON_VALUE + "; charset=utf-8"})
Убрал.

2020-09-30 12:25 UTC, ole279889 commented on src/main/java/team/mediasoft/study/java/ee/postservice/controller/PostalItemsController.java
> +    public String getItemStatus(@PathVariable String id) {
Ok

2020-09-30 12:29 UTC, ole279889 commented on src/main/java/team/mediasoft/study/java/ee/postservice/controller/PostalItemsController.java
> +                throw new NoItemsFoundException("Cannot find history! Item with id = " + id + " does not exists.");
Как минимум одна операция(регистрация) у item-ов есть всегда, поэтому если операций нет-значит, что item тоже не существует.

2020-09-30 12:31 UTC, ole279889 commented on src/main/java/team/mediasoft/study/java/ee/postservice/controller/PostalOperationsController.java
> +    public ResponseEntity<Void> itemDeparture(@RequestBody String item) {
Не знал об этом, попробовал сразу указывать как DTO - работает.

2020-09-30 12:32 UTC, ole279889 commented on src/main/java/team/mediasoft/study/java/ee/postservice/entity/dto/ErrorResponseBody.java
> +@JsonClassDescription
Убрано.

2020-09-30 12:32 UTC, ole279889 commented on src/main/java/team/mediasoft/study/java/ee/postservice/entity/dto/ItemContainerDTO.java
> +    @JsonGetter("item")
Убраны лишние.

2020-09-30 12:32 UTC, ole279889 commented on src/main/java/team/mediasoft/study/java/ee/postservice/entity/dto/PostalItemDTO.java
> +    @NotEmpty
Ok

2020-09-30 12:32 UTC, ole279889 commented on src/main/java/team/mediasoft/study/java/ee/postservice/exception/handler/GlobalExceptionHandler.java
> +            if (ex instanceof NoItemsFoundException) {
Сделал отдельные методы.

2020-09-30 12:33 UTC, ole279889 commented on src/main/java/team/mediasoft/study/java/ee/postservice/controller/PostalItemsController.java
> +        } catch (NonExistingItemException e) {
Ok

2020-09-30 12:33 UTC, ole279889 commented on src/main/java/team/mediasoft/study/java/ee/postservice/service/PostalService.java
> +    void officeArrival(PostalItem item, PostalOffice office) throws DataSourceException, DataMistmatchException, NoItemsFoundException, NonExistingItemException;
Одно из них лишнее, убрал.

2020-09-30 12:34 UTC, ole279889 commented on src/main/java/team/mediasoft/study/java/ee/postservice/repository/dbrepository/DBRepository.java
> +    private static String password;
Ok

2020-10-01 11:10 UTC, PavelAndryushenko approved these changes
Все в порядке, считаю, что можно мерджить. Есть ряд замечаний, но их можно (и нужно) поправить в ходе следующих доработок.

2020-10-01 11:10 UTC, PavelAndryushenko commented on src/main/java/team/mediasoft/study/java/ee/postservice/controller/PostalOperationsController.java
> +                    new Recipient(
Для таких преобразований лучше всего написать класс-маппер. Это может быть обычный маппер, а можно попробовать подкрутить mapstruct.

2020-10-01 11:10 UTC, PavelAndryushenko commented on src/main/java/team/mediasoft/study/java/ee/postservice/exception/handler/GlobalExceptionHandler.java
> +    @ExceptionHandler(value = Exception.class)
Идея была в том, чтобы уйти от метода, который срабатывает на все исключения - лучше сделать много методов со своим ExceptionHandler-ом

2020-10-01 11:20 UTC, merged