Jpa
ole279889/postservice pull request #9
Opened 2020-10-07 11:12 UTC by ole279889

2020-10-07 15:04 UTC, PavelAndryushenko requested changes
Материал по Hibernate и JPA применен правильно, все вполне корректно, есть несколько замечаний, который необходимо поправить перед мерджем.

2020-10-08 12:39 UTC, ole279889 commented on src/main/java/team/mediasoft/study/java/ee/postservice/entity/PostalItem.java
> +@NamedQueries({
Переместил.

2020-10-08 12:39 UTC, ole279889 commented on src/main/java/team/mediasoft/study/java/ee/postservice/entity/PostalItem.java
> +    @Convert(converter = PostalItemTypeEnumConverter.class)
Добавил сущности.

2020-10-08 12:40 UTC, ole279889 commented on src/main/java/team/mediasoft/study/java/ee/postservice/entity/PostalOperation.java
> +    @OneToOne(fetch = FetchType.EAGER)
Ок

2020-10-08 12:42 UTC, ole279889 commented on src/main/java/team/mediasoft/study/java/ee/postservice/entity/PostalOperation.java
> +    private Date date;
Убрал использование java.util.Date.

2020-10-08 12:42 UTC, ole279889 commented on src/main/java/team/mediasoft/study/java/ee/postservice/repository/dbrepository/PostalItemsRepositoryDb.java
> +            addItemPrSt.setString(1, item.getRecipientIndex());
Ок

2020-10-19 10:10 UTC, merged